name: "Reusable Base"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      is_main_pipeline:
        description: "Whether this is a Main (Non-PR) Pipeline"
        required: false
        type: boolean

jobs:
  Manage_Base_Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Hello from the Base"

