name: "Terraform Plan"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      is_main_pipeline:
        description: "Whether this is a Main (Non-PR) Pipeline"
        required: false
        type: boolean

jobs:
  PrintJob-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Printing from Job-1"
      - name: Get Date
        id: get-date
        if: ${{ inputs.is_main_pipeline }}
        run: |
          echo "time_value=$(date)" >> $GITHUB_OUTPUT
          sleep 10s
    outputs:
      time_value: ${{ steps.get-date.outputs.time_value }}

  PrintJob-2:
    needs:
      - PrintJob-1
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Hello from the Base. Is-Main-Pipeline: ${{ inputs.is_main_pipeline }}"
      - name: Apply Changes
        if: ${{ inputs.is_main_pipeline }}
        run: |
          echo "Current time = $(date)"
          echo "Time from last Job=${{ needs.PrintJob-1.outputs.time_value }}"
