name: "Reusable Base"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      is_main_pipeline:
        description: "Whether this is a Main (Non-PR) Pipeline"
        required: false
        type: boolean

jobs:
  Terraform-Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something 1st Time
        run: |
          echo "Printing from Job-1"
      - name: Get Date
        id: get-date
        if: ${{ inputs.is_main_pipeline }}
        run: |
          echo "time_value=$(date)" >> $GITHUB_OUTPUT
          sleep 10s
    outputs:
      time_value: ${{ steps.get-date.outputs.time_value }}

  Deploy-Resources:
    if: ${{ inputs.is_main_pipeline }}
    needs:
      - Terraform-Plan
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Print Something
        run: |
          echo "Hello from the Base. Is-Main-Pipeline: ${{ inputs.is_main_pipeline }}"
      - name: Wait a few seconds
        run: |
          sleep 10
      - name: Apply Changes
        if: ${{ inputs.is_main_pipeline }}
        run: |
          sleep 10
          echo "Current time = $(date)"
          echo "Time from last Job=${{ needs.PrintJob-1.outputs.time_value }}"
