name: "Reusable Base"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  Manage_Base_Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Hello from the Base"

