name: "Reusable Base"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      is_main_pipeline:
        description: "Whether this is a Main (Non-PR) Pipeline"
        required: false
        type: boolean

jobs:
  PrintJob-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Printing from Job-1"
      - name: Get Date
        id: get-date
        if: ${{ inputs.is_main_pipeline }}
        run: |
          echo "time_step1=$(date)" >> $GITHUB_OUTPUT
          echo "${{ steps.get-date.outputs.time_step1 }}"
    outputs:
      time_step1: ${{ steps.get-date.outputs.time_step1 }}

  PrintJob-2:
    needs:
      - PrintJob-1
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Hello from the Base. Is-Main-Pipeline: ${{ inputs.is_main_pipeline }}"
      - name: Apply Changes
        if: ${{ inputs.is_main_pipeline }}
        run: |
          echo "Applying changes for date=${{ needs.PrintJob-1.outputs.time_step1 }}"
