name: "Step-3: Workflow QA"
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize]
  push:
    branches: main

env:
  environment: "qa"

jobs:
  DeployInfra:
    with:
      environment: "qa"
      is_main_pipeline: false
    secrets: inherit
    uses: "./.github/workflows/base.yaml"
