name: "Step-2: Workflow QA"
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize]
  push:
    branches: main

env:
  environment: "qa"

jobs:
  Dispatch:
    name: Common Setup
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-dynamic-outputs.outputs.environment }}
    steps:
      - name: Set Outputs for Reusable
        id: set-dynamic-outputs
        run: |
          echo "environment=${{ env.environment }}" >> $GITHUB_OUTPUT

  PR: # This name is kept small on purpose to improve readability because of nesting workflow-names
    if: (github.event_name == 'pull_request')
    needs: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Print Something for PR
        run: |
          echo "Printing from Job-1"
      - name: Apply Changes
        if: (github.event_name == 'pull_request')
        run: |
          echo "Applying changes (only run for Main)"

  Main:
    if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    needs: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Print Something for Main
        run: |
          echo "Printing from Job-1"
      - name: Apply Changes
        if: (github.event_name == 'pull_request')
        run: |
          echo "Applying changes (only run for Main)"
