name: "Step-4: Workflow QA"
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize]
  push:
    branches: main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  deployments: write

env:
  environment: "qa"

jobs:
  Dispatch:
    name: Common Setup
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-dynamic-outputs.outputs.environment }}
    steps:
      - name: Set Outputs for Reusable
        id: set-dynamic-outputs
        run: |
          echo "environment=${{ env.environment }}" >> $GITHUB_OUTPUT

  Merge:
    if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    needs: Dispatch
    with:
      environment: ${{ needs.Dispatch.outputs.environment }}
      is_main_pipeline: true
    secrets: inherit
    uses: "./.github/workflows/base-step4.yaml"

  PR:
    if: (github.event_name == 'pull_request')
    needs: Dispatch
    with:
      environment: ${{ needs.Dispatch.outputs.environment }}
      is_main_pipeline: false
    secrets: inherit
    uses: "./.github/workflows/base-step4.yaml"
