name: "Infra Deployment: Live"
on:
  workflow_dispatch:

env:
  environment: "live"

jobs:
  PrintJob-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something 1st Time
        run: |
          echo "Printing from Job-1"
      - name: Apply Changes
        if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
        run: |
          echo "Applying changes (only run for Main)"

  PrintJob-2:
    needs:
      - PrintJob-1
    runs-on: ubuntu-latest
    steps:
      - name: Print Something 2nd Time
        run: |
          echo "Print Job-2"
      - name: Apply Changes
        if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
        run: |
          echo "Applying changes (only run for Main)"

  PrintJob-3:
    if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    needs:
      - PrintJob-2
    runs-on: ubuntu-latest
    steps:
      - name: Print Something 3rd Time
        run: |
          echo "Hello from the Base. Is-Main-Pipeline: ${{ inputs.is_main_pipeline }}"
      - name: Apply Changes
        if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
        run: |
          echo "Applying changes (only run for Main)"
