name: "Infra Deployment: FUJT (PR)"
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize]
  push:
    branches: main

env:
  environment: "qa"

jobs:
  DeployInfra:
    with:
      environment: "qa"
      is_main_pipeline: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) }}
    secrets: inherit
    uses: "./.github/workflows/base.yaml"
