name: "Infra Deployment: QA"
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize]
  push:
    branches: main

env:
  environment: "qa"

jobs:
  Dispatch:
    name: Common Setup
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-dynamic-outputs.outputs.environment }}
    steps:
      - name: Set Outputs for Reusable
        id: set-dynamic-outputs
        run: |
          echo "environment=${{ env.environment }}" >> $GITHUB_OUTPUT

  Main:
    if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    needs: Dispatch
    with:
      environment: ${{ needs.Dispatch.outputs.environment }}
      is_main_pipeline: true
    secrets: inherit
    uses: "./.github/workflows/base.yaml"

  PR: # This name is kept small on purpose to improve readability because of nesting workflow-names
    if: (github.event_name == 'pull_request')
    needs: Dispatch
    with:
      environment: ${{ needs.Dispatch.outputs.environment }}
      is_main_pipeline: false
    secrets: inherit
    uses: "./.github/workflows/base.yaml"
